# values.yaml

replicaCount: 1

image:
  repository: your-dockerhub-username/ghl-mcp-server
  tag: latest
  pullPolicy: Always

env:
  GHL_API_KEY: "your_private_integrations_api_key"  # Required
  GHL_LOCATION_ID: "your_location_id"               # Required
  GHL_BASE_URL: "https://services.leadconnectorhq.com"
  NODE_ENV: "production"
  PORT: 8000
  LOG_LEVEL: "info"
  CORS_ORIGINS: "*"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  annotations: {}

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi