# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghl-mcp-server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ghl-mcp-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ghl-mcp-server.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.env.PORT | default 8000 }}
          env:
            - name: GHL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ghl-mcp-server.fullname" . }}
                  key: GHL_API_KEY
            - name: GHL_LOCATION_ID
              value: {{ .Values.env.GHL_LOCATION_ID | quote }}
            - name: GHL_BASE_URL
              value: {{ .Values.env.GHL_BASE_URL | quote }}
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.env.CORS_ORIGINS | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.env.PORT | default 8000 }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.env.PORT | default 8000 }}
            initialDelaySeconds: 5
            periodSeconds: 10
